name: CD - Deploy ML Service

on:
  workflow_run:
    workflows: ["CI - Build and Push ML Service"]
    types:
      - completed

jobs:
  deploy:
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main'

    runs-on: self-hosted

    steps:
      - name: Create .env file from secrets
        run: echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" > .env

      - name: Pull latest Docker image
        run: docker pull manishsparihar/test-ml:latest

      - name: Stop and remove old container
        run: docker rm -f test-ml-container || true

      - name: Run new Docker Container with env file
        run: |
          docker run -d \
            -p 8000:8000 \
            --name test-ml-container \
            --env-file ./.env \
            manishsparihar/test-ml:latest
