name: CI - Build and Push ML Service

on:
  push:
    branches: ['main']
    # OPTIONAL BUT RECOMMENDED: Only run when files in ml/ change
    paths:
      - 'ml/**'

jobs:
  build-and-push:
    name: Build and Push ML image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          # Your secrets should be named DOCKERHUB_USERNAME and DOCKERHUB_TOKEN
          # for clarity, but I'm using your names to match your example.
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          # 1. Set the build context to the 'ml' sub-directory
          context: ./ml
          push: true
          # 2. Tag the image correctly for pushing to your Docker Hub repo
          tags: manishsparihar/test-ml:latest,manishsparihar/test-ml:${{ github.sha }}
